# Generated by Django 2.2.13 on 2022-10-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_institute_deatils'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='institute_deatils',
            new_name='institute_deatil',
        ),
    ]
