# Generated by Django 2.2.13 on 2022-10-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20221008_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute_deatil',
            name='zip_code',
            field=models.CharField(default='146001', max_length=6, verbose_name='zip code'),
        ),
    ]
