# Generated by Django 2.2.13 on 2022-10-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_auto_20221011_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='content',
        ),
        migrations.AddField(
            model_name='stories',
            name='listening_score',
            field=models.CharField(default='0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='stories',
            name='reading_score',
            field=models.CharField(default='0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='stories',
            name='speaking_score',
            field=models.CharField(default='0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='stories',
            name='writing_score',
            field=models.CharField(default='0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='stories',
            name='band_score',
            field=models.CharField(default='0.0', max_length=50),
        ),
    ]
