# Generated by Django 2.2.13 on 2022-10-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='featured',
        ),
    ]
