# Generated by Django 2.2.13 on 2022-10-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_remove_stories_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute_deatil',
            name='main_thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
