# Generated by Django 2.2.13 on 2022-10-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_institute_deatil_main_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='why_choose_learning_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
            ],
        ),
    ]
