# Generated by Django 2.2.13 on 2022-10-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_why_choose_learning_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why_choose_learning_point',
            name='line',
            field=models.TextField(max_length=40),
        ),
    ]
