# Generated by Django 2.2.13 on 2022-10-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_ourcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.TextField(blank=True, max_length=40, null=True)),
                ('author_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
