# Generated by Django 2.2.13 on 2022-10-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0018_contact_us_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_us_details',
            new_name='contact_us_detail',
        ),
    ]
