# Generated by Django 2.2.13 on 2022-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_auto_20221018_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us_detail',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='contact_us_detail',
            name='address2',
            field=models.TextField(default='Hoshiarpur-146001 PUNJAB'),
        ),
    ]
