# Generated by Django 2.2.13 on 2022-10-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0020_auto_20221018_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='e_mail',
            field=models.EmailField(max_length=254),
        ),
    ]
